In [160]:
!pip install pandas

Requirement already satisfied: pandas in .\.venv\Lib\site-packages (3.0.3)
Requirement already satisfied: numpy>=2.3.3 in .\.venv\Lib\site-packages (from pandas) (2.5.1)
Requirement already satisfied: python-dateutil>=2.8.2 in .\.venv\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in .\.venv\Lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in .\.venv\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [161]:
##inport the libraries
import pandas as pd

In [162]:
##Load the dataset
df=pd.read_csv(r"C:\Users\acer\Downloads\AmesHousing.csv")

In [163]:
##Display the first 5 rows
df.head()

,Unnamed: 0,MS_SubClass,MS_Zoning,Lot_Frontage,Lot_Area,Street,Alley,Lot_Shape,Land_Contour,Utilities,...,Fence,Misc_Feature,Misc_Val,Mo_Sold,Year_Sold,Sale_Type,Sale_Condition,Sale_Price,Longitude,Latitude
0,1,One_Story_1946_and_Newer_All_Styles,Residential_Low_Density,141,31770,Pave,No_Alley_Access,Slightly_Irregular,Lvl,AllPub,...,No_Fence,NaN,0,5,2010,WD,Normal,215000,-93.619754,42.054035
1,2,One_Story_1946_and_Newer_All_Styles,Residential_High_Density,80,11622,Pave,No_Alley_Access,Regular,Lvl,AllPub,...,Minimum_Privacy,NaN,0,6,2010,WD,Normal,105000,-93.619756,42.053014
2,3,One_Story_1946_and_Newer_All_Styles,Residential_Low_Density,81,14267,Pave,No_Alley_Access,Slightly_Irregular,Lvl,AllPub,...,No_Fence,Gar2,12500,6,2010,WD,Normal,172000,-93.619387,42.052659
3,4,One_Story_1946_and_Newer_All_Styles,Residential_Low_Density,93,11160,Pave,No_Alley_Access,Regular,Lvl,AllPub,...,No_Fence,NaN,0,4,2010,WD,Normal,244000,-93.617320,42.051245
4,5,Two_Story_1946_and_Newer,Residential_Low_Density,74,13830,Pave,No_Alley_Access,Slightly_Irregular,Lvl,AllPub,...,Minimum_Privacy,NaN,0,3,2010,WD,Normal,189900,-93.638933,42.060899

In [164]:
##Check the shape of the dataset
df.shape

(2930, 75)

In [165]:
##Datatypes of the dataset
df.dtypes

Unnamed: 0          int64
MS_SubClass           str
MS_Zoning             str
Lot_Frontage        int64
Lot_Area            int64
                   ...
Sale_Type             str
Sale_Condition        str
Sale_Price          int64
Longitude         float64
Latitude          float64
Length: 75, dtype: object

In [166]:
##Display Columns
df.columns

Index(['Unnamed: 0', 'MS_SubClass', 'MS_Zoning', 'Lot_Frontage', 'Lot_Area',
       'Street', 'Alley', 'Lot_Shape', 'Land_Contour', 'Utilities',
       'Lot_Config', 'Land_Slope', 'Neighborhood', 'Condition_1',
       'Condition_2', 'Bldg_Type', 'House_Style', 'Overall_Cond', 'Year_Built',
       'Year_Remod_Add', 'Roof_Style', 'Roof_Matl', 'Exterior_1st',
       'Exterior_2nd', 'Mas_Vnr_Type', 'Mas_Vnr_Area', 'Exter_Cond',
       'Foundation', 'Bsmt_Cond', 'Bsmt_Exposure', 'BsmtFin_Type_1',
       'BsmtFin_SF_1', 'BsmtFin_Type_2', 'BsmtFin_SF_2', 'Bsmt_Unf_SF',
       'Total_Bsmt_SF', 'Heating', 'Heating_QC', 'Central_Air', 'Electrical',
       'First_Flr_SF', 'Second_Flr_SF', 'Gr_Liv_Area', 'Bsmt_Full_Bath',
       'Bsmt_Half_Bath', 'Full_Bath', 'Half_Bath', 'Bedroom_AbvGr',
       'Kitchen_AbvGr', 'TotRms_AbvGrd', 'Functional', 'Fireplaces',
       'Garage_Type', 'Garage_Finish', 'Garage_Cars', 'Garage_Area',
       'Garage_Cond', 'Paved_Drive', 'Wood_Deck_SF', 'Open_Porch_SF',
       'Enclosed_Porch', 'Three_season_porch', 'Screen_Porch', 'Pool_Area',
       'Pool_QC', 'Fence', 'Misc_Feature', 'Misc_Val', 'Mo_Sold', 'Year_Sold',
       'Sale_Type', 'Sale_Condition', 'Sale_Price', 'Longitude', 'Latitude'],
      dtype='str')

In [167]:
##View infromation
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2930 entries, 0 to 2929
Data columns (total 75 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Unnamed: 0          2930 non-null   int64
 1   MS_SubClass         2930 non-null   str
 2   MS_Zoning           2930 non-null   str
 3   Lot_Frontage        2930 non-null   int64
 4   Lot_Area            2930 non-null   int64
 5   Street              2930 non-null   str
 6   Alley               2930 non-null   str
 7   Lot_Shape           2930 non-null   str
 8   Land_Contour        2930 non-null   str
 9   Utilities           2930 non-null   str
 10  Lot_Config          2930 non-null   str
 11  Land_Slope          2930 non-null   str
 12  Neighborhood        2930 non-null   str
 13  Condition_1         2930 non-null   str
 14  Condition_2         2930 non-null   str
 15  Bldg_Type           2930 non-null   str
 16  House_Style         2930 non-null   str
 17  Overall_Cond        2930 non-null   str
 18  Year_Built          2930 non-null   int64
 19  Year_Remod_Add      2930 non-null   int64
 20  Roof_Style          2930 non-null   str
 21  Roof_Matl           2930 non-null   str
 22  Exterior_1st        2930 non-null   str
 23  Exterior_2nd        2930 non-null   str
 24  Mas_Vnr_Type        1155 non-null   str
 25  Mas_Vnr_Area        2930 non-null   int64
 26  Exter_Cond          2930 non-null   str
 27  Foundation          2930 non-null   str
 28  Bsmt_Cond           2930 non-null   str
 29  Bsmt_Exposure       2930 non-null   str
 30  BsmtFin_Type_1      2930 non-null   str
 31  BsmtFin_SF_1        2930 non-null   int64
 32  BsmtFin_Type_2      2930 non-null   str
 33  BsmtFin_SF_2        2930 non-null   int64
 34  Bsmt_Unf_SF         2930 non-null   int64
 35  Total_Bsmt_SF       2930 non-null   int64
 36  Heating             2930 non-null   str
 37  Heating_QC          2930 non-null   str
 38  Central_Air         2930 non-null   str
 39  Electrical          2930 non-null   str
 40  First_Flr_SF        2930 non-null   int64
 41  Second_Flr_SF       2930 non-null   int64
 42  Gr_Liv_Area         2930 non-null   int64
 43  Bsmt_Full_Bath      2930 non-null   int64
 44  Bsmt_Half_Bath      2930 non-null   int64
 45  Full_Bath           2930 non-null   int64
 46  Half_Bath           2930 non-null   int64
 47  Bedroom_AbvGr       2930 non-null   int64
 48  Kitchen_AbvGr       2930 non-null   int64
 49  TotRms_AbvGrd       2930 non-null   int64
 50  Functional          2930 non-null   str
 51  Fireplaces          2930 non-null   int64
 52  Garage_Type         2930 non-null   str
 53  Garage_Finish       2930 non-null   str
 54  Garage_Cars         2930 non-null   int64
 55  Garage_Area         2930 non-null   int64
 56  Garage_Cond         2930 non-null   str
 57  Paved_Drive         2930 non-null   str
 58  Wood_Deck_SF        2930 non-null   int64
 59  Open_Porch_SF       2930 non-null   int64
 60  Enclosed_Porch      2930 non-null   int64
 61  Three_season_porch  2930 non-null   int64
 62  Screen_Porch        2930 non-null   int64
 63  Pool_Area           2930 non-null   int64
 64  Pool_QC             2930 non-null   str
 65  Fence               2930 non-null   str
 66  Misc_Feature        106 non-null    str
 67  Misc_Val            2930 non-null   int64
 68  Mo_Sold             2930 non-null   int64
 69  Year_Sold           2930 non-null   int64
 70  Sale_Type           2930 non-null   str
 71  Sale_Condition      2930 non-null   str
 72  Sale_Price          2930 non-null   int64
 73  Longitude           2930 non-null   float64
 74  Latitude            2930 non-null   float64
dtypes: float64(2), int64(33), str(40)
memory usage: 1.7 MB

In [168]:
##Check missing values
df.isnull().sum()

Unnamed: 0        0
MS_SubClass       0
MS_Zoning         0
Lot_Frontage      0
Lot_Area          0
                 ..
Sale_Type         0
Sale_Condition    0
Sale_Price        0
Longitude         0
Latitude          0
Length: 75, dtype: int64

In [169]:
##Check Duplicate values
df.duplicated().sum()

np.int64(0)

PHASE 2

In [170]:
##Count the total columns
len(df.columns)

75

In [171]:
##Seperate numerical column and categorical column
numerical_columns = df.select_dtypes(include=["int64","float64"]).columns

categorical_columns = df.select_dtypes(include=["object"]).columns

C:\Users\acer\AppData\Local\Temp\ipykernel_9612\3480877328.py:4: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_columns = df.select_dtypes(include=["object"]).columns

In [172]:
##Count the each type 
print("Numerical Columns:",len(numerical_columns))
print("Categorical Columns:",len(categorical_columns))

Numerical Columns: 35
Categorical Columns: 40

In [173]:
##Count the unique values
df["Neighborhood"].nunique()

28

In [174]:
##Check value Freaquency
df["Neighborhood"].value_counts()

Neighborhood
North_Ames                                 443
College_Creek                              267
Old_Town                                   239
Edwards                                    194
Somerset                                   182
Northridge_Heights                         166
Gilbert                                    165
Sawyer                                     151
Northwest_Ames                             131
Sawyer_West                                125
Mitchell                                   114
Brookside                                  108
Crawford                                   103
Iowa_DOT_and_Rail_Road                      93
Timberland                                  72
Northridge                                  71
Stone_Brook                                 51
South_and_West_of_Iowa_State_University     48
Clear_Creek                                 44
Meadow_Village                              37
Briardale                                   30
Bloomington_Heights                         28
Veenker                                     24
Northpark_Villa                             23
Blueste                                     10
Greens                                       8
Green_Hills                                  2
Landmark                                     1
Name: count, dtype: int64

PHASE 3

In [175]:
##Find ordinal columns
df["Heating_QC"].unique()

<StringArray>
['Fair', 'Typical', 'Excellent', 'Good', 'Poor']
Length: 5, dtype: str

In [176]:
##Create mapping
quality_map={
    "Poor":1,
    "Fair":2,
    "Typical":3,
    "Good":4,
    "Excellent":5
}

In [177]:
##Apply the mapping
df["Heating_QC"]=df["Heating_QC"].map(quality_map)

In [178]:
df["Heating_QC"].head()

0    2
1    3
2    3
3    5
4    4
Name: Heating_QC, dtype: int64

In [179]:
df.columns

Index(['Unnamed: 0', 'MS_SubClass', 'MS_Zoning', 'Lot_Frontage', 'Lot_Area',
       'Street', 'Alley', 'Lot_Shape', 'Land_Contour', 'Utilities',
       'Lot_Config', 'Land_Slope', 'Neighborhood', 'Condition_1',
       'Condition_2', 'Bldg_Type', 'House_Style', 'Overall_Cond', 'Year_Built',
       'Year_Remod_Add', 'Roof_Style', 'Roof_Matl', 'Exterior_1st',
       'Exterior_2nd', 'Mas_Vnr_Type', 'Mas_Vnr_Area', 'Exter_Cond',
       'Foundation', 'Bsmt_Cond', 'Bsmt_Exposure', 'BsmtFin_Type_1',
       'BsmtFin_SF_1', 'BsmtFin_Type_2', 'BsmtFin_SF_2', 'Bsmt_Unf_SF',
       'Total_Bsmt_SF', 'Heating', 'Heating_QC', 'Central_Air', 'Electrical',
       'First_Flr_SF', 'Second_Flr_SF', 'Gr_Liv_Area', 'Bsmt_Full_Bath',
       'Bsmt_Half_Bath', 'Full_Bath', 'Half_Bath', 'Bedroom_AbvGr',
       'Kitchen_AbvGr', 'TotRms_AbvGrd', 'Functional', 'Fireplaces',
       'Garage_Type', 'Garage_Finish', 'Garage_Cars', 'Garage_Area',
       'Garage_Cond', 'Paved_Drive', 'Wood_Deck_SF', 'Open_Porch_SF',
       'Enclosed_Porch', 'Three_season_porch', 'Screen_Porch', 'Pool_Area',
       'Pool_QC', 'Fence', 'Misc_Feature', 'Misc_Val', 'Mo_Sold', 'Year_Sold',
       'Sale_Type', 'Sale_Condition', 'Sale_Price', 'Longitude', 'Latitude'],
      dtype='str')

In [180]:

print(df["Exter_Cond"].unique())
print(df["Bsmt_Cond"].unique())
print(df["Bsmt_Exposure"].unique())
print(df["BsmtFin_Type_1"].unique())
print(df["BsmtFin_Type_2"].unique())
print(df["Functional"].unique())
print(df["Garage_Finish"].unique())
print(df["Garage_Cond"].unique())
print(df["Pool_QC"].unique())
print(df["Fence"].unique())
print(df["Paved_Drive"].unique())
print(df["Lot_Shape"].unique())
print(df["Land_Slope"].unique())

<StringArray>
['Typical', 'Good', 'Fair', 'Poor', 'Excellent']
Length: 5, dtype: str
<StringArray>
['Good', 'Typical', 'No_Basement', 'Poor', 'Fair', 'Excellent']
Length: 6, dtype: str
<StringArray>
['Gd', 'No', 'Mn', 'Av', 'No_Basement']
Length: 5, dtype: str
<StringArray>
['BLQ', 'Rec', 'ALQ', 'GLQ', 'Unf', 'LwQ', 'No_Basement']
Length: 7, dtype: str
<StringArray>
['Unf', 'LwQ', 'BLQ', 'Rec', 'No_Basement', 'GLQ', 'ALQ']
Length: 7, dtype: str
<StringArray>
['Typ', 'Mod', 'Min1', 'Min2', 'Maj1', 'Maj2', 'Sev', 'Sal']
Length: 8, dtype: str
<StringArray>
['Fin', 'Unf', 'RFn', 'No_Garage']
Length: 4, dtype: str
<StringArray>
['Typical', 'No_Garage', 'Fair', 'Good', 'Excellent', 'Poor']
Length: 6, dtype: str
<StringArray>
['No_Pool', 'Excellent', 'Good', 'Typical', 'Fair']
Length: 5, dtype: str
<StringArray>
['No_Fence', 'Minimum_Privacy', 'Good_Privacy', 'Good_Wood',
 'Minimum_Wood_Wire']
Length: 5, dtype: str
<StringArray>
['Partial_Pavement', 'Paved', 'Dirt_Gravel']
Length: 3, dtype: str
<StringArray>
['Slightly_Irregular', 'Regular', 'Moderately_Irregular', 'Irregular']
Length: 4, dtype: str
<StringArray>
['Gtl', 'Mod', 'Sev']
Length: 3, dtype: str

In [181]:
print(df["Pool_QC"].unique())
print(df["Fence"].unique())

<StringArray>
['No_Pool', 'Excellent', 'Good', 'Typical', 'Fair']
Length: 5, dtype: str
<StringArray>
['No_Fence', 'Minimum_Privacy', 'Good_Privacy', 'Good_Wood',
 'Minimum_Wood_Wire']
Length: 5, dtype: str

In [182]:
##Ordinal encoding of categorical features
mappings = {
    "Exter_Cond": {
        "Poor": 1,
        "Fair": 2,
        "Typical": 3,
        "Good": 4,
        "Excellent": 5
    },

    "Bsmt_Cond": {
        "No_Basement": 0,
        "Poor": 1,
        "Fair": 2,
        "Typical": 3,
        "Good": 4,
        "Excellent": 5
    },

    "Bsmt_Exposure": {
        "No_Basement": 0,
        "No": 1,
        "Mn": 2,
        "Av": 3,
        "Gd": 4
    },

    "BsmtFin_Type_1": {
        "No_Basement": 0,
        "Unf": 1,
        "LwQ": 2,
        "Rec": 3,
        "BLQ": 4,
        "ALQ": 5,
        "GLQ": 6
    },

    "BsmtFin_Type_2": {
        "No_Basement": 0,
        "Unf": 1,
        "LwQ": 2,
        "Rec": 3,
        "BLQ": 4,
        "ALQ": 5,
        "GLQ": 6
    },

    "Functional": {
        "Sal": 1,
        "Sev": 2,
        "Maj2": 3,
        "Maj1": 4,
        "Min2": 5,
        "Min1": 6,
        "Mod": 7,
        "Typ": 8
    },

    "Garage_Finish": {
        "No_Garage": 0,
        "Unf": 1,
        "RFn": 2,
        "Fin": 3
    },

    "Garage_Cond": {
        "No_Garage": 0,
        "Poor": 1,
        "Fair": 2,
        "Typical": 3,
        "Good": 4,
        "Excellent": 5
    },

    "Pool_QC": {
        "No_Pool": 0,
        "Poor": 1,
        "Fair": 2,
        "Typical": 3,
        "Good": 4,
        "Excellent": 5
    },

    "Fence": {
        "No_Fence": 0,
        "MnWw": 1,
        "GdWo": 2,
        "MnPrv": 3,
        "GdPrv": 4
    },
    "Paved_Drive":{
        "Dirt_Gravel": 0,
        "Partial_Pavement": 1,
        "Paved": 2
    },
    "Land_Slope": {
        "Sev": 1,
        "Mod": 2,
        "Gtl": 3
    },
    "Pool_QC": {
        "No_Pool": 0,
        "Fair": 1,
        "Typical": 2,
        "Good": 3,
        "Excellent": 4
    },
    "Fence": {
        "No_Fence": 0,
        "Minimum_Wood_Wire": 1,
        "Good_Wood": 2,
        "Minimum_Privacy": 3,
        "Good_Privacy": 4
    },
}


for col, mapping in mappings.items():
    if col in df.columns:
        df[col] = df[col].map(mapping)

In [183]:
df.head()

,Unnamed: 0,MS_SubClass,MS_Zoning,Lot_Frontage,Lot_Area,Street,Alley,Lot_Shape,Land_Contour,Utilities,...,Fence,Misc_Feature,Misc_Val,Mo_Sold,Year_Sold,Sale_Type,Sale_Condition,Sale_Price,Longitude,Latitude
0,1,One_Story_1946_and_Newer_All_Styles,Residential_Low_Density,141,31770,Pave,No_Alley_Access,Slightly_Irregular,Lvl,AllPub,...,0,NaN,0,5,2010,WD,Normal,215000,-93.619754,42.054035
1,2,One_Story_1946_and_Newer_All_Styles,Residential_High_Density,80,11622,Pave,No_Alley_Access,Regular,Lvl,AllPub,...,3,NaN,0,6,2010,WD,Normal,105000,-93.619756,42.053014
2,3,One_Story_1946_and_Newer_All_Styles,Residential_Low_Density,81,14267,Pave,No_Alley_Access,Slightly_Irregular,Lvl,AllPub,...,0,Gar2,12500,6,2010,WD,Normal,172000,-93.619387,42.052659
3,4,One_Story_1946_and_Newer_All_Styles,Residential_Low_Density,93,11160,Pave,No_Alley_Access,Regular,Lvl,AllPub,...,0,NaN,0,4,2010,WD,Normal,244000,-93.617320,42.051245
4,5,Two_Story_1946_and_Newer,Residential_Low_Density,74,13830,Pave,No_Alley_Access,Slightly_Irregular,Lvl,AllPub,...,3,NaN,0,3,2010,WD,Normal,189900,-93.638933,42.060899

In [184]:
for col in mappings.keys():
    print(col,df[col].isnull().sum())

Exter_Cond 0
Bsmt_Cond 0
Bsmt_Exposure 0
BsmtFin_Type_1 0
BsmtFin_Type_2 0
Functional 0
Garage_Finish 0
Garage_Cond 0
Pool_QC 0
Fence 0
Paved_Drive 0
Land_Slope 0

PHASE 4- FEATURE ENGINEERING

In [185]:
##Total Bathroom Count
df["Total_Bathrooms"] = (
    df["Full_Bath"] +
    (0.5 * df["Half_Bath"]) +
    df["Bsmt_Full_Bath"] +
    (0.5 * df["Bsmt_Half_Bath"])
)

In [186]:
print(df["Total_Bathrooms"])

0       2.0
1       1.0
2       1.5
3       3.5
4       2.5
       ...
2925    2.0
2926    2.0
2927    1.5
2928    2.0
2929    2.5
Name: Total_Bathrooms, Length: 2930, dtype: float64

In [187]:
##House Age
df["House_Age"] =df["Year_Sold"]-df["Year_Built"]

In [188]:
print(df["House_Age"])

0       50
1       49
2       52
3       42
4       13
        ..
2925    22
2926    23
2927    14
2928    32
2929    13
Name: House_Age, Length: 2930, dtype: int64

In [189]:
##Years since remodelling
df["Years_Since_Remodel"] = df["Year_Sold"]-df["Year_Remod_Add"]
print(df["Years_Since_Remodel"])

0       50
1       49
2       52
3       42
4       12
        ..
2925    22
2926    23
2927    14
2928    31
2929    12
Name: Years_Since_Remodel, Length: 2930, dtype: int64

In [190]:
##Total Porch Area
df["Total_Porch_SF"] = (
    df["Open_Porch_SF"] +
    df["Enclosed_Porch"] +
    df["Three_season_porch"] +
    df["Screen_Porch"]
)
print(df["Total_Porch_SF"])

0        62
1       120
2        36
3         0
4        34
       ...
2925      0
2926      0
2927     32
2928     38
2929     48
Name: Total_Porch_SF, Length: 2930, dtype: int64

In [191]:
##Total Living Area
df["Total_Living_Area"] = (df["Gr_Liv_Area"] +df["Total_Bsmt_SF"])
print(df["Total_Living_Area"])

0       2736
1       1778
2       2658
3       4220
4       2557
        ...
2925    2006
2926    1766
2927    1882
2928    2778
2929    2996
Name: Total_Living_Area, Length: 2930, dtype: int64

In [192]:
##Total Outdoor area
df["Total_Outdoor_Area"] =(df["Wood_Deck_SF"] +df["Total_Porch_SF"] +df["Pool_Area"])
print(df["Total_Outdoor_Area"])

0       272
1       260
2       429
3         0
4       246
       ...
2925    120
2926    164
2927    112
2928    278
2929    238
Name: Total_Outdoor_Area, Length: 2930, dtype: int64

In [193]:
##New Columns
df[[
    "Total_Bathrooms",
    "House_Age",
    "Years_Since_Remodel",
    "Total_Porch_SF",
    "Total_Living_Area",
    "Total_Outdoor_Area"
]].head()

,Total_Bathrooms,House_Age,Years_Since_Remodel,Total_Porch_SF,Total_Living_Area,Total_Outdoor_Area
0,2.0,50,50,62,2736,272
1,1.0,49,49,120,1778,260
2,1.5,52,52,36,2658,429
3,3.5,42,42,0,4220,0
4,2.5,13,12,34,2557,246

PHASE 5

In [194]:
##Dataset information
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2930 entries, 0 to 2929
Data columns (total 81 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Unnamed: 0           2930 non-null   int64
 1   MS_SubClass          2930 non-null   str
 2   MS_Zoning            2930 non-null   str
 3   Lot_Frontage         2930 non-null   int64
 4   Lot_Area             2930 non-null   int64
 5   Street               2930 non-null   str
 6   Alley                2930 non-null   str
 7   Lot_Shape            2930 non-null   str
 8   Land_Contour         2930 non-null   str
 9   Utilities            2930 non-null   str
 10  Lot_Config           2930 non-null   str
 11  Land_Slope           2930 non-null   int64
 12  Neighborhood         2930 non-null   str
 13  Condition_1          2930 non-null   str
 14  Condition_2          2930 non-null   str
 15  Bldg_Type            2930 non-null   str
 16  House_Style          2930 non-null   str
 17  Overall_Cond         2930 non-null   str
 18  Year_Built           2930 non-null   int64
 19  Year_Remod_Add       2930 non-null   int64
 20  Roof_Style           2930 non-null   str
 21  Roof_Matl            2930 non-null   str
 22  Exterior_1st         2930 non-null   str
 23  Exterior_2nd         2930 non-null   str
 24  Mas_Vnr_Type         1155 non-null   str
 25  Mas_Vnr_Area         2930 non-null   int64
 26  Exter_Cond           2930 non-null   int64
 27  Foundation           2930 non-null   str
 28  Bsmt_Cond            2930 non-null   int64
 29  Bsmt_Exposure        2930 non-null   int64
 30  BsmtFin_Type_1       2930 non-null   int64
 31  BsmtFin_SF_1         2930 non-null   int64
 32  BsmtFin_Type_2       2930 non-null   int64
 33  BsmtFin_SF_2         2930 non-null   int64
 34  Bsmt_Unf_SF          2930 non-null   int64
 35  Total_Bsmt_SF        2930 non-null   int64
 36  Heating              2930 non-null   str
 37  Heating_QC           2930 non-null   int64
 38  Central_Air          2930 non-null   str
 39  Electrical           2930 non-null   str
 40  First_Flr_SF         2930 non-null   int64
 41  Second_Flr_SF        2930 non-null   int64
 42  Gr_Liv_Area          2930 non-null   int64
 43  Bsmt_Full_Bath       2930 non-null   int64
 44  Bsmt_Half_Bath       2930 non-null   int64
 45  Full_Bath            2930 non-null   int64
 46  Half_Bath            2930 non-null   int64
 47  Bedroom_AbvGr        2930 non-null   int64
 48  Kitchen_AbvGr        2930 non-null   int64
 49  TotRms_AbvGrd        2930 non-null   int64
 50  Functional           2930 non-null   int64
 51  Fireplaces           2930 non-null   int64
 52  Garage_Type          2930 non-null   str
 53  Garage_Finish        2930 non-null   int64
 54  Garage_Cars          2930 non-null   int64
 55  Garage_Area          2930 non-null   int64
 56  Garage_Cond          2930 non-null   int64
 57  Paved_Drive          2930 non-null   int64
 58  Wood_Deck_SF         2930 non-null   int64
 59  Open_Porch_SF        2930 non-null   int64
 60  Enclosed_Porch       2930 non-null   int64
 61  Three_season_porch   2930 non-null   int64
 62  Screen_Porch         2930 non-null   int64
 63  Pool_Area            2930 non-null   int64
 64  Pool_QC              2930 non-null   int64
 65  Fence                2930 non-null   int64
 66  Misc_Feature         106 non-null    str
 67  Misc_Val             2930 non-null   int64
 68  Mo_Sold              2930 non-null   int64
 69  Year_Sold            2930 non-null   int64
 70  Sale_Type            2930 non-null   str
 71  Sale_Condition       2930 non-null   str
 72  Sale_Price           2930 non-null   int64
 73  Longitude            2930 non-null   float64
 74  Latitude             2930 non-null   float64
 75  Total_Bathrooms      2930 non-null   float64
 76  House_Age            2930 non-null   int64
 77  Years_Since_Remodel  2930 non-null   int64
 78  Total_Porch_SF       2930 non-null   int64
 79  Total_Living_Area    2930 non-null   int64
 80  Total_Outdoor_Area   2930 non-null   int64
dtypes: float64(3), int64(51), str(27)
memory usage: 1.8 MB

In [195]:
##Check missing values
df.isnull().sum()

Unnamed: 0             0
MS_SubClass            0
MS_Zoning              0
Lot_Frontage           0
Lot_Area               0
                      ..
House_Age              0
Years_Since_Remodel    0
Total_Porch_SF         0
Total_Living_Area      0
Total_Outdoor_Area     0
Length: 81, dtype: int64

In [196]:
##Check if any duplicated rows are there
df.duplicated().sum()

np.int64(0)

In [197]:
##Display last 5 rows
df.tail()

,Unnamed: 0,MS_SubClass,MS_Zoning,Lot_Frontage,Lot_Area,Street,Alley,Lot_Shape,Land_Contour,Utilities,...,Sale_Condition,Sale_Price,Longitude,Latitude,Total_Bathrooms,House_Age,Years_Since_Remodel,Total_Porch_SF,Total_Living_Area,Total_Outdoor_Area
2925,2926,Split_or_Multilevel,Residential_Low_Density,37,7937,Pave,No_Alley_Access,Slightly_Irregular,Lvl,AllPub,...,Normal,142500,-93.604776,41.988964,2.0,22,22,0,2006,120
2926,2927,One_Story_1946_and_Newer_All_Styles,Residential_Low_Density,0,8885,Pave,No_Alley_Access,Slightly_Irregular,Low,AllPub,...,Normal,131000,-93.602680,41.988314,2.0,23,23,0,1766,164
2927,2928,Split_Foyer,Residential_Low_Density,62,10441,Pave,No_Alley_Access,Regular,Lvl,AllPub,...,Normal,132000,-93.606847,41.986510,1.5,14,14,32,1882,112
2928,2929,One_Story_1946_and_Newer_All_Styles,Residential_Low_Density,77,10010,Pave,No_Alley_Access,Regular,Lvl,AllPub,...,Normal,170000,-93.600190,41.990921,2.0,32,31,38,2778,278
2929,2930,Two_Story_1946_and_Newer,Residential_Low_Density,74,9627,Pave,No_Alley_Access,Regular,Lvl,AllPub,...,Normal,188000,-93.599996,41.989265,2.5,13,12,48,2996,238

PHASE 6

In [198]:
df.to_csv("AmesHousing_Feature_Engineered.csv", index=False)

# Project Conclusion

In this project, I successfully performed feature engineering on the Ames Housing dataset.

## Tasks Completed
- Imported and explored the dataset
- Identified numerical and categorical features
- Performed ordinal encoding
- Created new engineered features
- Validated the transformed dataset
- Exported the final feature-engineered dataset

## Tools Used
- Python
- Pandas

## Output
A clean and feature-engineered dataset ready for machine learning and further data analysis.

PHASE 7- House Prediction using Scikit-Learn

In [199]:
##Install the scikit-learn
!pip install scikit-learn

Requirement already satisfied: scikit-learn in .\.venv\Lib\site-packages (1.9.0)
Requirement already satisfied: numpy>=1.24.1 in .\.venv\Lib\site-packages (from scikit-learn) (2.5.1)
Requirement already satisfied: scipy>=1.10.0 in .\.venv\Lib\site-packages (from scikit-learn) (1.18.0)
Requirement already satisfied: joblib>=1.4.0 in .\.venv\Lib\site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: narwhals>=2.0.1 in .\.venv\Lib\site-packages (from scikit-learn) (2.23.0)
Requirement already satisfied: threadpoolctl>=3.5.0 in .\.venv\Lib\site-packages (from scikit-learn) (3.6.0)

In [200]:
##import the libraries
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)

In [201]:
##Create features(X) Target(Y)
X = df.drop("Sale_Price", axis=1)
y = df["Sale_Price"]

In [202]:
##Check the shape
print("Features Shape:", X.shape)
print("Target Shape:", y.shape)

Features Shape: (2930, 80)
Target Shape: (2930,)

In [203]:
X=pd.get_dummies(X,drop_first=True)

In [204]:
##Split The Dataset

In [205]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [206]:
##Check the shapes
print("X_train:",X_train.shape)
print("X_test :",X_test.shape)
print("y_train:",y_train.shape)
print("y_test :",y_test.shape)

X_train: (2344, 236)
X_test : (586, 236)
y_train: (2344,)
y_test : (586,)

LINEAR MODEL REGRESSION

In [207]:
X.dtypes

Unnamed: 0                int64
Lot_Frontage              int64
Lot_Area                  int64
Land_Slope                int64
Year_Built                int64
                          ...
Sale_Condition_AdjLand     bool
Sale_Condition_Alloca      bool
Sale_Condition_Family      bool
Sale_Condition_Normal      bool
Sale_Condition_Partial     bool
Length: 236, dtype: object

In [208]:
X.select_dtypes(include=["object","string"]).columns

Index([], dtype='str')

In [209]:
## Create the Linear Regression model
model = LinearRegression()
# Train the model using the training data
model.fit(X_train,y_train)

LinearRegression()

In [210]:
##Make the Prediction of house
y_pred = model.predict(X_test)

In [211]:
##Compare Actual price vs Predicted Price
prediction_df = pd.DataFrame({
    "Actual Price": y_test.values,
    "Predicted Price": y_pred
})
prediction_df.head(10)

   Actual Price  Predicted Price
0        161000    137236.994399
1        116000    109462.521621
2        196500    190710.540499
3        123600    147048.793229
4        126000    125190.233343
5        174190    195092.953792
6        200000    140913.944458
7        148500    146834.344648
8         88750    115053.496910
9        409900    321914.909713

In [214]:
##evaluate the model
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = mse ** 0.5
r2 = r2_score(y_test, y_pred)
print("Mean Absolute Error (MAE):", mae)
print("Mean Squared Error (MSE):", mse)
print("Root Mean Squared Error (RMSE):", rmse)
print("R² Score:", r2)

Mean Absolute Error (MAE): 19095.619951662928
Mean Squared Error (MSE): 1009908408.2508714
Root Mean Squared Error (RMSE): 31779.0561258649
R² Score: 0.8740377460847275

In [216]:
##Display the Metrics
print(f"MAE : {mae:.2f}")
print(f"MSE : {mse:.2f}")
print(f"RMSE: {rmse:.2f}")
print(f"R²  : {r2:.4f}")

MAE : 19095.62
MSE : 1009908408.25
RMSE: 31779.06
R²  : 0.8740

In [217]:
!pip install joblib

Requirement already satisfied: joblib in .\.venv\Lib\site-packages (1.5.3)

In [218]:
import joblib
joblib.dump(model, "House_Price_Model.pkl")

['House_Price_Model.pkl']

# Project Conclusion

## Objective

Build a machine learning model to predict house prices using the Ames Housing dataset.

## Tasks Completed

- Loaded the dataset
- Explored the data
- Performed feature engineering
- Encoded ordinal categorical features
- Converted categorical variables into numerical features
- Split the dataset into training and testing sets
- Trained a Linear Regression model
- Predicted house prices
- Evaluated the model using MAE, MSE, RMSE, and R² Score

## Tools Used

- Python
- Pandas
- Scikit-learn

## Machine Learning Algorithm

- Linear Regression

## Outcome

Successfully built a machine learning model capable of predicting house prices using engineered features.